apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-cp4mcm-anyuid
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ibm-cp4mcm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

