apiVersion: charts.helm.k8s.io/v1
kind: Xl
metadata:
  namespace: turbonomic
  name: xl-release
spec:
  # Default values copied from <project_dir>/helm-charts/xl/values.yaml

  # Default values for xl.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  # Any changes run : kubectl apply -f deploy/crds/charts_v1alpha1_xl_cr.yaml -n turbonomic
  nginxingress: 
    enabled: false
  openshiftingress: 
    enabled: true
  #ingress:
    # domain: *.turbonomic.com
  # Global settings
  global:
    registry: index.docker.io
#    imageUsername: turbouser
#    imagePassword: turbopassword
    repository: turbonomic
#    storageClassName: managed-nfs-storage
#    securityContext:
#      fsGroup: 1000650000 
    tag: 8.3.2
    #externalIP: 10.0.2.15
    #externalDbIP: 10.0.2.15
    #externalTimescaleDBIP: 10.0.2.15
    externalArangoDBName: arango.turbo.svc.cluster.local
    #enableExternalSecrets: true

# Component selector - Probes
  actionscript:
    enabled: true
  actionstream-kafka:
    enabled: true
  appdynamics:
    enabled: true
  appinsights:
    enabled: true
  aws:
    enabled: true
  azure:
    enabled: true
  dynatrace:
    enabled: true
  hpe3par:
    enabled: true
  horizon:
    enabled: false
  hyperflex:
    enabled: false
  hyperv:
    enabled: true
  instana:
    enabled: true
  kubeturbo:
    enabled: true
  netapp:
    enabled: true
  nutanix:
    enabled: true
  oneview:
    enabled: true
  prometheus:
    enabled: true
  prometurbo:
    enabled: true
  pure:
    enabled: true
  scaleio:
    enabled: true
  servicenow:
    enabled: true
  ucs:
    enabled: true
  vcenter:
    enabled: true
  vmax:
    enabled: true
  vmm:
    enabled: true
  wmi:
    enabled: true
  snmp:
    enabled: true
  mssql:
    enabled: true
  mysql:
    enabled: true
  oracle:
    enabled: true
  tomcat:
    enabled: true
  jvm:
    enabled: true
  newrelic:
    enabled: true
  udt:
    enabled: true
  websphere:
    enabled: true 
  weblogic:
    enabled: true
