apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-management-orchestrator
  namespace: openshift-marketplace
spec:
  displayName: IBM Management Orchestrator Catalog
  publisher: IBM
  sourceType: grpc
  image: {{ .Values.mcm.config.catalogSourceImage }} # ${CP4MCM_CATALOGSOURCE_IMAGE}
  updateStrategy:
    registryPoll:
      interval: 45m