apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-management-orchestrator
  namespace: openshift-operators
spec:
  channel: {{.Values.mcm.config.subscriptionChannel}}
  installPlanApproval: Automatic
  name: ibm-management-orchestrator
  source: ibm-management-orchestrator
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-management-orchestrator.v{{.Values.mcm.config.subscriptionCsv}} #${CP4MCM_SUBSCRIPTION_CSV}