apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "200"
    argocd.argoproj.io/hook: PreSync
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: acm-pullsecret-job-sa-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - patch