---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  nodeSelector:
      node-role.kubernetes.io/infra: ""
  overrides:
    components:
    - name: cluster-proxy-addon
      enabled: false
    - name: cluster-backup
      enabled: false
  imagePullSecret: multiclusterhub-pull-secret