apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management

resources:
  - cr.yaml
  - crb.yaml
  - sa.yaml
  - acm-setup.yaml
  - instance.yaml
  - console-link-crb.yaml
  - rhacm-console-link.yaml