apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap-prometheus.yaml
  - deployment.yaml
  - namespace.yaml
  - serviceaccount.yaml
  - anyuid-rolebinding.yaml
