apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: cluster
  namespace: external-secrets
spec:
  provider:
    ibm:
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: ibm-secret
            namespace: kube-system
            key: apiKey
      serviceUrl: >-
        https://16b75d1e-9b7a-48d7-8729-8137d091ff31.au-syd.secrets-manager.appdomain.cloud