apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: cluster
  namespace: external-secrets
spec:
  provider:
    ibm:
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: ibm-secret
            namespace: kube-system
            key: apiKey
      serviceUrl: >-
        https://bcfa8c9a-2684-4bdd-92e1-46ca00288460.au-syd.secrets-manager.appdomain.cloud