---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cr.yaml
  - crb.yaml
  - sa.yaml
  - object-bucket-claim.yaml
  - observability-setup.yaml
  - multiclusterobservability.yaml