apiVersion: v1
kind: ServiceAccount
metadata:
  name: cli-job-sa
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "200"
    argocd.argoproj.io/hook: PreSync