kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - overlays/stable-2.1

patches:
-  target:
     kind: Subscription
     name: ansible-automation-platform
   patch: |-
    - op: replace
      path: /metadata/namespace
      value: 'ansible-automation-platform'
    - op: add
      path: /spec/installPlanApproval
      value: Automatic