kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - aggregate/default

patches:
-  target:
     kind: Job
     name: create-cluster-init-bundle
     namespace: rhacs-operator
   patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: >-
        registry.redhat.io/openshift4/ose-cli:latest
-  target:
     kind: Central
     name: central
     namespace: rhacs-operator
   patch: |-
    - op: add
      path: /spec/central/persistence/persistentVolumeClaim/storageClassName
      value: >-
        ocs-storagecluster-ceph-rbd