kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-sa-console-link-crb
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ibm-infra-automation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: route-get
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: route-get
  namespace: ibm-infra-automation
rules:
  - verbs:
    - get
    apiGroups:
    - route.openshift.io
    resources:
    - routes
