kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-monitoring-exporter-clusteradmin
subjects:
  - kind: ServiceAccount
    name: ibm-monitoring-exporter
    namespace: ibm-common-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin