apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: amazon/cloudwatch-agent:1.247348.0b251302
    target:
      kind: Deployment
      name: cwagent-prometheus
  

secretGenerator:
  - name: aws-credentials
    files: 
    - credentials
    type: Opaque
    namespace: amazon-cloudwatch

configMapGenerator:
  - name: prometheus-cwagentconfig
    files: 
    - cwagentconfig.json
    namespace: amazon-cloudwatch

      