---
apiVersion: cluster.open-cluster-management.io/v1aplha1
kind: Placement
metadata:
  name: last-mile-gitops 
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: vendor
          operator: "In"
          values:
          - OpenShift