apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

bases:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: quay-bridge-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable-3.6'
