apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: quay-setup-rolebinding
  annotations:
    argocd.argoproj.io/sync-wave: "200"
    argocd.argoproj.io/hook: PreSync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: quay-setup-job-sa-role 
subjects:
  - kind: ServiceAccount
    name: cli-quay-setup-job-sa
    namespace: quay-registry 